create extension if not exists pgcrypto;

create table if not exists public.users (
    id uuid primary key default gen_random_uuid(),
    username text not null unique,
    email text not null unique,
    password text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.blacklist_tokens (
    id bigint generated by default as identity primary key,
    token text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.interview_reports (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.users(id) on delete cascade,
    job_description text not null,
    resume text not null default '',
    self_description text,
    match_score integer check (match_score between 0 and 100),
    technical_questions jsonb not null default '[]'::jsonb,
    behavior_questions jsonb not null default '[]'::jsonb,
    skill_gaps jsonb not null default '[]'::jsonb,
    preparation_plan jsonb not null default '[]'::jsonb,
    title text not null default 'Interview Analysis & Resume',
    resume_html text not null default '',
    resume_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'interview_reports'
          and column_name = 'user'
    ) and not exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'interview_reports'
          and column_name = 'user_id'
    ) then
        alter table public.interview_reports rename column "user" to user_id;
    end if;
end $$;

create index if not exists interview_reports_user_created_at_idx
    on public.interview_reports (user_id, created_at desc);

alter table public.users disable row level security;
alter table public.blacklist_tokens disable row level security;
alter table public.interview_reports disable row level security;